---
 - hosts: nodeAPP
   tasks:
      - name: Instalando dependencias NVM
        command: apt-get install curl build-essential libssl-dev -y

      - name: Instalando NVM
        shell: curl curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh -o install_nvm.sh; bash install_nvm.sh

      - name: Atualizar terminal source
        shell: /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 6.11.4 && nvm alias default 6.11.4"

      - name: Instalando NPM
        apt: name=npm

      - name: Instalando dependencia NODEJS
        shell: npm install -g express; npm link express

